language: java

before_install:
  - docker build -t gregzealley/name-matcher-api .

## Run integration tests
script: ./build.sh

## Only build when merging into master
branches:
  only:
    - "master"
