language: java

before_install:
  - docker build -t gregzealley/name-matcher-api .

## Run integration tests
script: "mvn verify -Pintegration-test"

## Only build when merging into master
branches:
  only:
    - "master"
