language: java

## Run integration tests
script: ./build.sh

after_success:
  - docker build -t gregzealley/name-matcher-api .

## Only build when merging into master
branches:
  only:
    - "master"
